using System.ComponentModel.DataAnnotations;

namespace LibraryManagementSystem.Models
{
    /// 
    /// A Member's ask to borrow a specific item through the public portal.
    /// Deliberately kept separate from BorrowRecord: a request is not yet a
    /// real loan. It only becomes a BorrowRecord once Admin reviews and
    /// approves it (see BorrowRequestController.Approve), which also flips
    /// the item's Status to "Borrowed". This two-step flow exists so Members
    /// never lend items to themselves directly - Admin makes the final call.
    /// 
    public class BorrowRequest
    {
        /// Primary key, auto-generated by the database.
        public int Id { get; set; }

        /// Foreign key to the item being requested.
        public int ItemId { get; set; }

        /// Navigation property to the requested item, populated via .Include() in queries.
        public Item? Item { get; set; }

        /// Foreign key to the borrower who made the request.
        public int BorrowerId { get; set; }

        /// Navigation property to the requesting borrower, populated via .Include() in queries.
        public Borrower? Borrower { get; set; }

        /// The date/time the Member submitted this request.
        [Display(Name = "Requested On")]
        public DateTime RequestDate { get; set; } = DateTime.Now;

        /// 
        /// Current state of the request. Must be one of exactly three values:
        /// "Pending" (awaiting Admin's decision), "Approved", or
        /// "Rejected". Stored as a plain string, compared exactly by
        /// BorrowRequestController.
        /// 
        [Required]
        public string Status { get; set; } = "Pending";

        /// 
        /// Set to the Id of the BorrowRecord created when this request was
        /// approved, so the request and the resulting loan can be traced
        /// back to each other. Stays null for pending or rejected requests.
        /// 
        public int? BorrowRecordId { get; set; }
    }
}
