using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryManagementSystem.Models
{
    /// 
    /// Represents one real, confirmed loan of an item to a borrower. Created
    /// either directly by Reception (BorrowRecordController) or automatically
    /// when Reception approves a BorrowRequest submitted by a Member. This is
    /// the single source of truth for "who currently has what" and for fine
    /// calculation on return.
    /// 
    public class BorrowRecord
    {
        /// Primary key, auto-generated by the database.
        public int Id { get; set; }

        /// Foreign key to the item that was borrowed.
        public int ItemId { get; set; }

        /// Navigation property to the borrowed item, populated via .Include() in queries.
        public Item? Item { get; set; }

        /// Foreign key to the borrower who took the item out.
        public int BorrowerId { get; set; }

        /// Navigation property to the borrower, populated via .Include() in queries.
        public Borrower? Borrower { get; set; }

        /// The date/time the item was actually handed over.
        [Display(Name = "Borrow Date")]
        public DateTime BorrowDate { get; set; } = DateTime.Now;

        /// The date the item is expected back. Defaults to a 14-day loan period.
        [Display(Name = "Due Date")]
        public DateTime DueDate { get; set; } = DateTime.Now.AddDays(14);

        /// 
        /// The date/time the item was actually returned. Null while the loan
        /// is still active; this is the flag used throughout the app to tell
        /// active loans apart from completed ones.
        /// 
        [Display(Name = "Return Date")]
        public DateTime? ReturnDate { get; set; }

        /// 
        /// The fine charged for a late return, calculated once at return time
        /// (see BorrowRecordController.ReturnItem). Stays 0.00 for on-time
        /// returns and for loans still in progress. Explicit decimal(8,2)
        /// column type avoids EF Core's default-precision warning.
        /// 
        [Display(Name = "Fine Amount ($)")]
        [Column(TypeName = "decimal(8,2)")]
        public decimal FineAmount { get; set; } = 0.00m;
    }
}
