using System.ComponentModel.DataAnnotations;

namespace LibraryManagementSystem.Models
{
    /// 
    /// A library patron who can have items lent to them. This is deliberately
    /// separate from ApplicationUser: every borrower has these contact
    /// details, but only borrowers who registered publicly also have a login
    /// account (see ApplicationUserId below). Admin can create borrowers
    /// directly without them ever having an account.
    /// 
    public class Borrower
    {
        /// Primary key, auto-generated by the database.
        public int Id { get; set; }

        /// The borrower's full name.
        [Required]
        [Display(Name = "Full Name")]
        public string FullName { get; set; } = string.Empty;

        /// Contact email address, also used as the login username if they registered.
        [Required]
        [EmailAddress]
        public string Email { get; set; } = string.Empty;

        /// Contact phone number (optional).
        public string Phone { get; set; } = string.Empty;

        /// 
        /// Foreign key to AspNetUsers.Id. Set automatically when this borrower
        /// signed up through the public Register page, which links their new
        /// login account to a matching Borrower profile. Left null for
        /// borrowers Admin created manually without a login, since
        /// not every borrower needs to be able to log in themselves.
        /// 
        public string? ApplicationUserId { get; set; }
    }
}
