using System.Globalization;
using System.Text;

namespace LibraHub.Services;

/// <summary>
/// Tiny dependency-free PDF writer (Helvetica / Courier text, A4, automatic page breaks and a footer with
/// "generated by, date/time, page x of y" – spec F7 business rules). Enough for the three report exports.
/// </summary>
public class SimplePdf
{
    record Line(string Text, double Size, bool Mono, bool Bold);
    readonly List<Line> _lines = new();
    readonly string _footerLeft;

    public SimplePdf(string generatedBy) =>
        _footerLeft = $"Generated by {Clean(generatedBy)} on {DateTime.Now:yyyy-MM-dd HH:mm}";

    public SimplePdf Title(string t) { _lines.Add(new(t, 20, false, true)); _lines.Add(new("", 6, false, false)); return this; }
    public SimplePdf Heading(string t) { _lines.Add(new("", 6, false, false)); _lines.Add(new(t, 13, false, true)); return this; }
    public SimplePdf Text(string t) { _lines.Add(new(t, 10, false, false)); return this; }
    public SimplePdf Row(params string[] cols) { _lines.Add(new(string.Join("", cols), 9, true, false)); return this; }
    public SimplePdf Blank() { _lines.Add(new("", 8, false, false)); return this; }

    /// <summary>Pads cells to fixed widths for monospaced table rows.</summary>
    public static string[] Cells(int[] widths, params string[] v) =>
        v.Select((s, i) => (Clean(s).Length > widths[i] - 1 ? Clean(s)[..(widths[i] - 1)] : Clean(s)).PadRight(widths[i])).ToArray();

    static string Clean(string s) =>
        new string((s ?? "").Select(c => c < 32 || c > 126 ? (c == '’' ? '\'' : '?') : c).ToArray());

    static string Esc(string s) => Clean(s).Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
    static string N(double d) => d.ToString("0.##", CultureInfo.InvariantCulture);

    public byte[] Build()
    {
        const double W = 595, H = 842, M = 50, Top = H - 60, Bottom = 70;
        var pages = new List<List<(double y, Line l)>>();
        var cur = new List<(double, Line)>(); double y = Top;
        foreach (var l in _lines)
        {
            var step = l.Size * 1.35;
            if (y - step < Bottom) { pages.Add(cur); cur = new(); y = Top; }
            y -= step; cur.Add((y, l));
        }
        pages.Add(cur);

        var objs = new List<string>();           // 1-based object list
        int Add(string body) { objs.Add(body); return objs.Count; }
        Add("<< /Type /Catalog /Pages 2 0 R >>");
        Add("");                                  // pages placeholder (object 2)
        Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>");       // F1 = 3
        Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>");  // F2 = 4
        Add("<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>");         // F3 = 5

        var kids = new List<int>();
        for (int p = 0; p < pages.Count; p++)
        {
            var sb = new StringBuilder();
            foreach (var (py, l) in pages[p])
            {
                if (l.Text.Length == 0) continue;
                var font = l.Mono ? "F3" : l.Bold ? "F2" : "F1";
                sb.Append($"BT /{font} {N(l.Size)} Tf {N(M)} {N(py)} Td ({Esc(l.Text)}) Tj ET\n");
            }
            sb.Append($"BT /F1 8 Tf {N(M)} 35 Td ({Esc(_footerLeft)}) Tj ET\n");
            sb.Append($"BT /F1 8 Tf {N(W - M - 60)} 35 Td (Page {p + 1} of {pages.Count}) Tj ET\n");
            var content = sb.ToString();
            var cid = Add($"<< /Length {Encoding.ASCII.GetByteCount(content)} >>\nstream\n{content}endstream");
            var pid = Add($"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {N(W)} {N(H)}] /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R >> >> /Contents {cid} 0 R >>");
            kids.Add(pid);
        }
        objs[1] = $"<< /Type /Pages /Kids [{string.Join(" ", kids.Select(k => $"{k} 0 R"))}] /Count {kids.Count} >>";

        var outSb = new StringBuilder("%PDF-1.4\n");
        var offsets = new List<int>();
        for (int i = 0; i < objs.Count; i++)
        {
            offsets.Add(Encoding.ASCII.GetByteCount(outSb.ToString()));
            outSb.Append($"{i + 1} 0 obj\n{objs[i]}\nendobj\n");
        }
        var xref = Encoding.ASCII.GetByteCount(outSb.ToString());
        outSb.Append($"xref\n0 {objs.Count + 1}\n0000000000 65535 f \n");
        foreach (var o in offsets) outSb.Append($"{o:D10} 00000 n \n");
        outSb.Append($"trailer\n<< /Size {objs.Count + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF");
        return Encoding.ASCII.GetBytes(outSb.ToString());
    }
}
