using System.ComponentModel.DataAnnotations;

namespace LibraryManagementSystem.Models
{
    /// 
    /// Abstract base class for anything the library lends out.
    /// Book, Music, and Toy all inherit from this class and add their own
    /// type-specific fields. It is marked abstract because a bare "Item" has
    /// no real-world meaning on its own - every item in the system must be
    /// one of the three concrete subclasses.
    /// 
    public abstract class Item
    {
        /// Primary key, auto-generated by the database.
        public int Id { get; set; }

        /// 
        /// The unique code printed on the item's physical label, used by
        /// Reception to look items up when lending/returning them.
        /// 
        [Required]
        public string LibraryCode { get; set; } = string.Empty;

        /// Display name of the item (e.g. book title, album name, toy name).
        [Required]
        public string Name { get; set; } = string.Empty;

        /// Free-text description shown to staff and on the public search page.
        public string Description { get; set; } = string.Empty;

        /// 
        /// Current lifecycle state of the item. Must be one of exactly four
        /// values: "Available", "Borrowed", "Damaged", "Destroy". Stored as a
        /// plain string rather than an enum, so every controller that reads or
        /// writes Status compares against these exact strings.
        /// 
        [Required]
        public string Status { get; set; } = "Available";
    }
}
